name: CI

on:
  push:
    paths:
        - '**/*.sh'

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run / Test script
      run: |
        ./find_transcript_ids.sh --TEST