name: CI/CD Bash Script

on:
  push:
    paths:
      - './findTranscriptID.sh'

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: show CWD
      run: pwd
    - name: cat script
      run: cat ./findTranscriptionIDs.sh
    - name: Run / Test script
      run: |
        ./findTranscriptionIDs.sh