name: CI/CD Bash Script

on: [push, pull_request]

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Bash
      run: |
        sudo apt-get update
        sudo apt-get install -y bash

    - name: Run my bash script
      run: |
        chmod +x ./findTranscriptionIDs.sh
        ./findTranscriptionIDs.sh