name: CI/CD Bash Script

on:
  push:
    paths:
      - './find_transcript_ids.sh'
      - './.find_transcript_ids_vars_n_functions'
      - './.shell_functions'

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run / Test script
      run: |
        ./find_transcript_ids.sh --TEST